<form method="post" action="<?php echo $this->url(array('action' => $this->action))?>">
  
  <?php if ($this->action == 'update'): ?>
  <input type="hidden" name="submit_id" value="<?php echo $this->submit_id ?>" />
  <?php endif ?>
  
  <dl>
    <dt><label for="title">Title</label></dt>
    <dd>
      <?php echo $this->error($this->form, 'title')?>
      <input type="text" name="form[title]" id="title" value="<?php echo $this->escape($this->form['title'])?>" />
    </dd>
  </dl>
  
  <dl>
    <dt><label for="datetime">Datetime</label></dt>
    <dd>
      <?php echo $this->error($this->form, 'datetime')?>
      <?php echo $this->widget('keithwood:datetimeentry', array('id' => 'datetime', 'name' => 'form[datetime]', 'value' => $this->form['datetime'], 'config' => array('phpDatetimeFormat' => 'Y-m-d H:i:s'))) ?>
      <!--<input type="text" name="form[datetime]" id="datetime" value="<?php echo $this->escape($this->form['datetime'])?>" />-->
    </dd>
  </dl>
  
  <dl>
    <dt><label for="teaser">Teaser</label></dt>
    <dd>
      <?php echo $this->error($this->form, 'teaser')?>
      <textarea name="form[teaser]" id="teaser"><?php echo $this->escape($this->form['teaser'])?></textarea>
    </dd>
  </dl>
  
  <dl>
    <dt><label for="message">Message</label></dt>
    <dd>
      <?php echo $this->error($this->form, 'message')?>
      <textarea name="form[message]" id="message"><?php echo $this->escape($this->form['message'])?></textarea>
    </dd>
  </dl>
  <dl>
    <dd>
      <input type="submit" value="<?php echo $this->action?>" />
    </dd>
  </dl>
</form>